### ISSUE TITLE
关于Apple ID登录Mac App Store的方法咨询

### ISSUE THREAD

**Issue by yo1995** [darkhandz/XPS15-9550-High-Sierra#1]
您好，参考了您的方法成功完善了系统，但始终没能解决的是App Store登录问题。
查到iMessage等应用需要三码无法搞定倒是无所谓，但很希望能够登录App Store下载应用。
不知您是否解决了这个问题？是通过什么方法解决的呢？
谢谢。

补充一下，看到过您的汇总中提到的编译dsdt的方法。参考了Rehabman的原帖，https://github.com/RehabMan/OS-X-Null-Ethernet
似乎直接将提供的ssdt拷进去也可以？但我还是没能实现。

机内是killer网卡，用的360WiFi来联网。不知道未驱动机内的网卡是否对这一步骤造成影响。

**Comment by darkhandz** [comment]
360WiFi属于外置网卡，你需要：
- 下载上面提到的[NullEthernet](https://bitbucket.org/RehabMan/os-x-null-ethernet/downloads/)
- 然后`sudo cp -r 拖NullEthernet.kext过来 /Library/Extensions/`
- 然后`sudo kextcache -i /`
- 重启，然后按照我本教程里的`网卡顺序修正`操作，当作顺序不正确的情况处理，重新添加时，要把以太网作为第一个添加的项。

应该就可以了。

**Comment by yo1995** [comment]
http://buildingahackintosh.weebly.com/networking-in-sierra.html
按照您的方法和上述链接都尝试过了，始终没能内建出以太网来
个人不太了解系统驱动的原理，有几种猜测
1 可能是外置网卡的驱动和nullethernet产生冲突
2 可能是SSDT未能正确工作

目前状况是NullEthernet.kext放到了/S/L/E和/L/E两个目录下，分别用kext utility和sudo kextcache -i /操作过，SSDT-RMNE.aml也放到了EFI分区相应目录下，也重复尝试过删除NetworkInterfaces.plist这个文件，仍旧无法在系统偏好设置 - 网络中添加虚拟的以太网卡…

…实在不知道该如何查错 :sob:

**Comment by darkhandz** [comment]
是我漏说了SSDT-RMNE.aml。你把你config.plist上传我看看。

**Comment by yo1995** [comment]
如下，我把SSDT-RMNE.aml添加到了sortedorder尾部，不知是否合理。
[config.zip](https://github.com/darkhandz/XPS15-9550-High-Sierra/files/1219792/config.zip)

**Comment by darkhandz** [comment]
@yo1995 config.plist似乎没有问题，建议安装NullEthernet重启后，执行`kextstat | grep -i null` 看看有没有结果，以确定是否加载。

**Comment by yo1995** [comment]
好的，我试了一下没有输出。
如果不行我先暂时搁置了，花费了好长时间 :disappointed:

**Comment by darkhandz** [comment]
没有输出的话，NullEthernet并没有加载成功。

**Comment by yo1995** [comment]
更新一下，这几天重新搞了一番，最终可以上了。问题似乎出在下列几个因素之一：
- kext放置的位置，之前是SLE后来我放到了clover下的kext文件夹
- ACPI SortedOrder，我把RehabMan的NullEthernet的SSDT-RMNE.aml顺序提升了，不知道是否有影响
- 安装了一些依赖库，不过目测没啥影响
- 换了个USB-RJ45转换器

多谢之前的帮助！:smile:
