### ISSUE TITLE
黑苹果的触摸板手势是否支持？

### ISSUE THREAD

**Issue by kousan94** [darkhandz/XPS15-9550-High-Sierra#10]
已按教程完美复原了您的结果，但现在是触摸板部分的问题，发现没有手势功能，但在教程当中并没有说明，想问问黑手大大能不能使用，亦或者是我的配置不同与您的设备配置导致的呢？希望得到您的回复。谢谢

**Comment by scottsanett** [comment]
VoodooPS2Touchpad手势少，可以考虑换[ApplePS2SmartTouchpad](http://forum.osxlatitude.com/index.php?/topic/1948-elan-focaltech-and-synaptics-smart-touchpad-driver-mac-os-x/)然后自定义手势

**Comment by darkhandz** [comment]
Voodoo的手势并不怎么好用……我只用鼠标了。
如楼上热心同学建议，可以试试，但是不知道对10.13支持如何。

**Comment by kousan94** [comment]
@scottsanett  尝试更换了您所说的驱动，根据教程安装好了之后发现手势支持的没几个，找到一个相关教程http://bbs.pcbeta.com/viewthread-1734262-1-1.html，发现对于10.13来说并不是支持的很好，可能需要等正式版本才可以。说不定哪天有时间再弄回10.12，总之谢谢。

**Comment by scottsanett** [comment]
@kousan94 你可以试试我的repo里的ApplePSSmartTrackpad，在偏好设置里把launchpad设置成F12（原本是dashboard，被我设置成了F7），Notification Center设置成Ctrl Alt N，支持的手势还是挺多的
