### ISSUE TITLE
升级到HS正式版以后无法调节亮度？

### ISSUE THREAD

**Issue by scottsanett** [darkhandz/XPS15-9550-High-Sierra#11]

**Comment by Jeremyye114** [comment]
参考wmchris的背光教程自己patch一遍～，https://github.com/wmchris/DellXPS15-9550-OSX/blob/master/Additional/PatchAppleBacklight_v2/readme.md 或者试试我自己重新patch的，不一定有用
[AppleBacklightInjector.kext.zip](https://github.com/darkhandz/XPS15-9550-High-Sierra/files/1339571/AppleBacklightInjector.kext.zip)

**Comment by scottsanett** [comment]
啥都没动它自己解决了🌚

**Comment by darkhandz** [comment]
第一次重启不能调节很正常，重启一次之后就可以了。教程有说明

> 进入桌面后建议你再重启一次系统，不然亮度调节无效。
