### ISSUE TITLE
碰到的几个问题

### ISSUE THREAD

**Issue by getmonyinfo** [darkhandz/XPS15-9550-High-Sierra#18]
1.使用`辅助工具`中的配置文件，全新安装最后一步会出现`验证固件时发生错误`，两个镜像都这样（10.13 正式版， 10.13.1），可以通过添加FirmwareFeatures为0xFC0FE136解决。

2.使用你的最新版配置文件，无法进入系统，  可以进入clover，但是选择启动选项后，亮屏，没有任何输出。

3. 启动时偶尔会出现fs_set_inode_with_hint:7825: failed to load inode ， 看到别人的解决办法是重新拷贝一份apfs.efi, 不知你有没有碰到过。

**Comment by darkhandz** [comment]
第3个应该是apfs.efi版本与系统版本不匹配的问题，你可以用最新版本的apfs.efi替换driver64UEFI里面的。
第2个问题，你可以一个个查看我前两天的所有commit，看看我都改了什么，你可以逐步应用这些更改，看看具体到哪个commit导致出问题。
