### ISSUE TITLE
无法使用复制粘贴

### ISSUE THREAD

**Issue by inksnw** [darkhandz/XPS15-9550-High-Sierra#21]
加入CoreDisplayFixup.kext并打了4K补丁后,无法使用复制粘贴,曾经有一次安装,升级系统后好了,后来安装升级一半就失败了,复制粘贴也就再不能用.
这里有些相关的 https://github.com/Floris497/mac-pixel-clock-patch-V2/issues/211

**Comment by darkhandz** [comment]
不了解4k的情况，可以请教热心的 @gujiangjiang 同学。

**Comment by scottsanett** [comment]
CoreDisplayFixup就足够了不需要pixel clock patch

**Comment by gujiangjiang** [comment]
对于小白来说，建议使用手动Patch，Lilu的插件越少越好，Lilu的插件严重依赖Lilu，Lilu稍有问题，这些插件就全部挂了

**Comment by inksnw** [comment]
只用CoreDisplayFixup不打pixel clock patch确实好了,感谢感谢
