### ISSUE TITLE
想请教一下关于SSD的trim的问题？

### ISSUE THREAD

**Issue by soulomoon** [darkhandz/XPS15-9550-High-Sierra#23]
看到最新的clover，config.plist, 原先关于trim的patch是disable的，请问一下是什么原因呢？
1 是因为使用这个patch会出现硬盘崩溃？
2 是因为这个patch已经无效？
3 是因为patch和其他patch或者kext出现冲突？

**Comment by darkhandz** [comment]
详情可以[看看这里](https://www.tonymacx86.com/threads/readme-common-problems-in-10-13-high-sierra.233582/)，在APFS下开启TRIM会影响电池电量显示。如果你是HFS+J文件系统，可以启用TRIM。

但是即使disable了，依然感觉APFS启动好慢，要不是开发环境还原比较麻烦，我都重装一次改回HFS+J了。

**Comment by soulomoon** [comment]
蟹蟹解答，
我同时装了10.12.6和10.13.1, 都是HFS+
这两这版本都可以用您的clover启动，
本没有用过APFS，
不过感觉启动是版本的锅
high sierra的开机比sierra开机慢好多。

**Comment by darkhandz** [comment]
我也是觉得sierra比较好……不是搞iOS开发的话感觉不用升10.13
