### ISSUE TITLE
4K版本现在有解决方案吗？

### ISSUE THREAD

**Issue by scottsanett** [darkhandz/XPS15-9550-High-Sierra#3]

**Comment by darkhandz** [comment]
肯定有的，只是我没有4K硬件，所以我并不方便在未实测的情况下瞎写，所以不去研究了。

**Comment by scottsanett** [comment]
在1080P下你的配置是直接可以驱动显卡吗？

**Comment by darkhandz** [comment]
@scottsanett Optimus的独显是暂时没有解决方案的，如果你是说核显HD520，是可以驱动的。

**Comment by zhanglong5460** [comment]
按照wmchris 10.12的教程，将coredisplayfixup.kext 和lilu.kext 放到efi的10.13文件夹里就可以驱动集显

**Comment by scottsanett** [comment]
@zhanglong5460 这个经过了测试吗？

**Comment by zhanglong5460** [comment]
@scottsanett 10.12上可以，10.13应该可以。

**Comment by scottsanett** [comment]
已解决 [solution](https://github.com/scottsanett/M5510-4K-High-Sierra-Installation/blob/master/README.md)
