### ISSUE TITLE
安装Clover那个步骤硬盘efi没有多出clover文件夹

### ISSUE THREAD

**Issue by huanghaibin-dev** [darkhandz/XPS15-9550-High-Sierra#33]
你好，我的系统也是你提供的那个，步骤很顺利，但是到硬盘引导的那个步骤，安装Clover后，硬盘efi文件夹下没有出现clover文件夹，请问这是什么问题？boot版本和你的一样

**Comment by soulomoon** [comment]
可能是你安装的位置不一样吧？

**Comment by huanghaibin-dev** [comment]
不是，我以前11.6和12.1的版本也是按这些教程安装的，这次其它都很顺利，就是安装clover这一步安装完看硬盘efi分区时没有clover文件夹，重新试了很多次也没用，这就奇怪了
