### ISSUE TITLE
在10.13.2/3的系统中，可能开机出现does printf work！！

### ISSUE THREAD

**Issue by yaozaiyu** [darkhandz/XPS15-9550-High-Sierra#39]
http://www.insanelymac.com/forum/topic/330598-solution-does-printf-work-freeze-with-osxaptiov2/#entry2553095
这个是w'mchri的解决方法，没看懂。只可能出现在osxaptiov2中，也就是加了slide=x的里面

**Comment by scottsanett** [comment]
我也碰到了这个问题，解决方案就是进入recovery mode，打开终端
```
cd /Volumes/Macintosh\ HD （此处改为macOS系统分区的名字）
sudo kextcache -i .
```
然后重启

**Comment by VAllens** [comment]
这才是正确的打开方式。
我也是如此，但我是因为放错kexts引起的，所以打开recovery mode后，我要先替换成正确的kexts，然后再重建缓存和权限。

**Comment by yaozaiyu** [comment]
我现在想根本上解决这个问题，我是亮度调节失效放入LE，然后修复权限，然后就出现了这个报错，有没有根治 的办法

**Comment by VAllens** [comment]
没试过亮度调节，晚上回去试试
