### ISSUE TITLE
iTunes闪退？

### ISSUE THREAD

**Issue by scottsanett** [darkhandz/XPS15-9550-High-Sierra#4]
PB6上iTunes闪退频繁，又遇到类似问题的吗？

**Comment by WalkerPan** [comment]
@scottsanett 请使用终端： sudo nvram -c，这是4k的那个kext导致的，运行后多重启几次就好了

**Comment by scottsanett** [comment]
每次开机都需要运行这个命令吗？

**Comment by WalkerPan** [comment]
@scottsanett 闪退的时候就运行就好了

**Comment by Jeremyye114** [comment]
@scottsanett @WalkerPan 不需要这样，llu (1.2.1+) 和 shiki (2.1.1+)config配置文件中的启动参数(即Boot/Arguments)里加入 shikigva=16，见此贴http://bbs.pcbeta.com/viewthread-1768496-1-1.html
用了两天貌似无闪退

**Comment by scottsanett** [comment]
@Jeremyye114 `shikigva=16` 貌似是默认开启的，看起来好像确实是解决了的问题，非常感谢！
