### ISSUE TITLE
syscl的xps13已经实现触屏手势了，4k屏的快来测测

### ISSUE THREAD

**Issue by yaozaiyu** [darkhandz/XPS15-9550-High-Sierra#44]
https://github.com/syscl/XPS9350-macOS

**Comment by scottsanett** [comment]
具体的变化在哪个commit？好像没有看到？

**Comment by yaozaiyu** [comment]
https://pan.baidu.com/s/1Y2Wfw2tYNQssrQUw0oohow
可以下下来，看一下

**Comment by scottsanett** [comment]
大概不是给9550用的？我装上了触摸板键盘都不可用

**Comment by yaozaiyu** [comment]
@scottsanett xps13的额

**Comment by yaozaiyu** [comment]
@scottsanett 已经实现功能，看操作说明，第三步如果sortedorder如果本来就是空的，也可以不填；

**Comment by scottsanett** [comment]
@yaozaiyu 你已经尝试了吗？

**Comment by yaozaiyu** [comment]
@scottsanett 是的，完美实现功能！

**Comment by scottsanett** [comment]
@yaozaiyu 需要删除VoodooPS2Controller吗？

**Comment by hunao0221** [comment]
在qq群你里面看见一个触屏手势，感觉挺不错,我机器现在的情况是网页都没办法触屏
滚动
[https://pan.baidu.com/s/1Wj5vRcv1BBHtgzcT4qpfDg](url)

**Comment by yaozaiyu** [comment]
不需要删东西

**Comment by yaozaiyu** [comment]
安装方法：


1.dsdt pathes
Comment: change _STA to XSTA in Device GPI0
Find: 5F535441
Replace: 58535441
TgtBridge: 47504930

Comment: change _CRS to XCRS in Device TPD1
Find: 5F435253
Replace: 58435253
TgtBridge: 54504431


2. hotpatch
acpi/patched目录下的文件放到对应位置

3. SSDT-I2C.aml名字写到config中Acpi/SortedOrder中（如果sortedorder为空则不需要加入）

4. 2个驱动添加到对应位置

**Comment by hunto** [comment]
请问各位，安装后有什么变化吗？
我装了之后触屏和以前一样，没有发现有触摸手势

**Comment by scottsanett** [comment]
没变化+1

**Comment by yaozaiyu** [comment]
加这个群吧
633956297

**Comment by Herrengit** [comment]
请问最后如何

**Comment by Herrengit** [comment]
请问要如何操作

**Comment by xyx208** [comment]
大家试试这个吧：
把SSDT-XOSI.aml这个放到apci/patched
然后用不用附件的kext放到kexts里，可以实现二指，三指，四指，只是合盖后，就会重启，各位大佬能不能看看研究一下，如何能完美使用：
链接: https://pan.baidu.com/s/1lxrqgrvfrI6FmY0-LuikLA 密码: 48wd

我的机器：xps-9550 i7 6700hq  16Gram 4k屏幕。

**Comment by darkhandz** [comment]
@xyx208 你这个是啥版本的VoodooI2C？官方的v2.0.1和你这个不一样……不过你这个可以用，官网的反而不能用，所以很奇怪……

10.13.6 并没有遇到你说的盒盖重启问题。

**Comment by xyx208** [comment]
> @xyx208 你这个是啥版本的VoodooI2C？官方的v2.0.1和你这个不一样……不过你这个可以用，官网的反而不能用，所以很奇怪……
> 
> 10.13.6 并没有遇到你说的盒盖重启问题。
黑手大佬 ，你的clover是不是github上的版本呀？

**Comment by darkhandz** [comment]
@xyx208 了解了一下前因后果，你这个是native分支的VoodooI2C，作者们逆向分析了MagicTrackpad2的协议，让我们的触摸板通过VoodooI2C模拟它的行为，但是因为有些问题没解决（比如按下触摸板物理按键并拖拽，松开物理按键后拖拽依然不结束，要手指离开触摸板才能让拖拽结束），所以作者不打算编译Release。

我的配置修改过不少，和repo上的有些区别，暂时不会发

**Comment by xyx208** [comment]
> @xyx208 了解了一下前因后果，你这个是native分支的VoodooI2C，作者们逆向分析了MagicTrackpad2的协议，让我们的触摸板通过VoodooI2C模拟它的行为，但是因为有些问题没解决（比如按下触摸板物理按键并拖拽，松开物理按键后拖拽依然不结束，要手指离开触摸板才能让拖拽结束），所以作者不打算编译Release。
> 
> 我的配置修改过不少，和repo上的有些区别，暂时不会发

我现在面临的最大问题是，合盖会重启，我这个主板是7月份才换的，不知道和这个有没有关系。唉！

**Comment by scottsanett** [comment]
@xyx208 考慮CPU有關的kexts有問題，比如CPUFriend或者之前的X86PlatformInjector. VoodooI2C不會導致睡死的問題。

**Comment by darkhandz** [comment]
@xyx208 怀疑硬件有问题的话，你应该用win去测试，而不是黑苹果

**Comment by xyx208** [comment]
> @xyx208 怀疑硬件有问题的话，你应该用win去测试，而不是黑苹果

windows下没有问题，在黑果下，只要换成2.03的VoodooI2C也不会有这样的问题，只是手势只能三指。
