### ISSUE TITLE
关于触屏手势的问题

### ISSUE THREAD

**Issue by hunao0221** [darkhandz/XPS15-9550-High-Sierra#46]
我的机器目前触屏完全没有手势，连滚动网页都不行，但是昨天看见群里有个哥们发的小视频，看见他的触屏手势还挺6的，不知道具体是怎么实现的。
[https://pan.baidu.com/s/1Wj5vRcv1BBHtgzcT4qpfDg](url)

**Comment by scottsanett** [comment]
我也行，只是驱动是从touchbase买的

**Comment by Herrengit** [comment]
能提供一下驱动吗

**Comment by VAllens** [comment]
现在还有人用High-Sierra?
