### ISSUE TITLE
想尝试装beta 8，结果卡在IOConsoleUsers：gIOScreenLockState 3，hs 0，now 0 ，sm 0x0

### ISSUE THREAD

**Issue by Jeremyye114** [darkhandz/XPS15-9550-High-Sierra#5]
![tim 20170904111820](https://user-images.githubusercontent.com/26202271/30010507-c466e094-9162-11e7-8db4-1f95aca0a1b7.jpg)
想尝试装beta 8，结果卡在IOConsoleUsers：gIOScreenLockState 3，hs 0，now 0 ，sm 0x0 ，在远景搜了下说替换IntelGraphicsFixup.kext和Lilu.kext，但无效果~有哪位大神知道麻烦指点下~

要么等正式版再研究..........................

**Comment by shawzh** [comment]
Add the node under to the CLOVER/config.plist/Devices(Enable it to boot)
```
 <key>FakeID</key>
 <dict>
     <key>IntelGFX</key>
     <string>0x12345678</string>
 </dict>
```

**Comment by scottsanett** [comment]
4K版本吗？安装的时候把igplatformid改成0x12345678就好了，我直接用的darkhandz的kexts

**Comment by scottsanett** [comment]
@shawzh Does your laptop come with 4K as well? Have you had any problems with iTunes? (Constantly crashing etc)

**Comment by Jeremyye114** [comment]
@scottsanett 昨晚试了已经进去了，原来win下编辑config文件根本没用~前期尝试加0x12345678无法识别，不过卡在第二次重启卡在macOS 未能安装在您的电脑上，更新固件发生错误，在论坛搜了好像是需要修改firmware，不知道你有无遇到~晚上再回去试试

**Comment by scottsanett** [comment]
@Jeremyye 今天还遇到一次…我把系统安装文件写入了两个usb，今天写入的usb报错，之前写入的usb就没有…简直是玄学

**Comment by Jeremyye114** [comment]
@shawzh Thanks，the problem has been solved，but is show macOS could not be instanllde on your computer An error occurred while verifying firmware !Someone say i need to modify config.plist/SMBIOS

![firmware-erroren](https://user-images.githubusercontent.com/26202271/30054803-e14bfd2c-925f-11e7-84d7-d8474387a114.jpg)

**Comment by Jeremyye114** [comment]
@scottsanett  我也是4K，有采用apfs格式么？话说跟12.5有区别么，还是体验更差？

**Comment by scottsanett** [comment]
我不知道怎么才能不用apfs…和12.5区别不大，桌面动画貌似更流畅了一些，现在主要的问题就是iTunes崩溃和电源更新不及时，我的5510 repo里面有提到

**Comment by scottsanett** [comment]
而且iTunes崩溃应该不是iTunes的问题，应该和图形有关，我在用0x12345678启动的时候从来没崩，用0x191b0000各种姿势地崩

**Comment by shawzh** [comment]
@scottsanett  我也是4k屏with5510，iTunes也是崩溃。
@Jeremyye114 同样遇到过这个问题，用苹果给的磁盘工具把硬盘全盘格式化后（本来硬盘里有个win10）没有出现这个问题，格式化时选择的HFS格式，安装完成后自动转换成APFS了

**Comment by shawzh** [comment]
@scottsanett 你遇到过鼠标箭头突然变大一下，一闪而过，然后恢复正常吗？

**Comment by scottsanett** [comment]
shawzh: 这估计是feature，你多摇摇鼠标就自然变大了，这是在贴心的告诉你鼠标在这里（苹果大概默认你摇鼠标是因为找不到它）

**Comment by scottsanett** [comment]
@shawzh 可能得看看其他笔记本型号4K屏有没有iTunes崩溃这个问题……10.13的iTunes崩到我现在用10.12的iTunes都提心吊胆

**Comment by Piping** [comment]
@Jeremyye114 Have you solved the firmware verifying error?
