### ISSUE TITLE
直升10.14无限重启，求解决思路

### ISSUE THREAD

**Issue by Endermanpoi** [darkhandz/XPS15-9550-High-Sierra#56]
10.13.6版本AppStore直升10.14，系统内完成处理后，重启进入安装，显示正在安装后重启，clover选原引导可以打开10.13.6，clover版本最新，但EFI和驱动保持这个教程的版本，求解决思路

**Comment by darkhandz** [comment]
这个版本不适合10.14，这几天抽时间试试10.14，能用的话再起一个repo

**Comment by darkhandz** [comment]
10.14的repo已创建，感兴趣的可以自己试试。

**Comment by Endermanpoi** [comment]
给大佬递冰阔洛，刚刚折腾崩了，正好来抢救了(*^o^*)

**Comment by chenjunyuan1996** [comment]
请问如何直升啊，刚刚也陷入了无限重启

**Comment by Endermanpoi** [comment]
> 请问如何直升啊，刚刚也陷入了无限重启

重启的时候选择不加载驱动启动，然后玄学就可以装了

**Comment by chenjunyuan1996** [comment]
> > 请问如何直升啊，刚刚也陷入了无限重启
> 
> 重启的时候选择不加载驱动启动，然后玄学就可以装了

试了下，不重启，能装，但是进度条走完就不动了，很迷

**Comment by nick2834** [comment]
我进BIOS设置uefi  然后点击 Add Boot Option 显示file system not found怎么搞
