### ISSUE TITLE
10.13的亮度调节快捷键失效

### ISSUE THREAD

**Issue by gujiangjiang** [darkhandz/XPS15-9550-High-Sierra#8]
Smart触摸板驱动，10.11和10.12都正常的亮度调节快捷键在10.13上面无效了。。。

**Comment by scottsanett** [comment]
我也是ApplePS2SmartTouchpad驱动没碰到这个问题，你说的是F11和F12吗？

**Comment by gujiangjiang** [comment]
@scottsanett 是的。。。F11和F12按下没效果了。。。10.12是可以的。。。

**Comment by Jeremyye114** [comment]
@gujiangjiang 是按没效果还是系统不能调节亮度？FN+F11？VoodooPS2Controller是否可以呢？？？

**Comment by gujiangjiang** [comment]
@scottsanett 按下去没反应，12的时候可以的，亮度是可以正常调节的，就是亮度快捷键不能用了。。。

我试一下你的BRT6看看。。。我的和你的不一样。。。

**Comment by gujiangjiang** [comment]
测试还是不行，用了你的帖子里的 BRT6还是不行，F11和F12按下去依旧没有反应。。。音量正常，亮度不行。。。。

**Comment by scottsanett** [comment]
@gujiangjiang 我是直接用darkhandz的acpi，你有用AppleBacklightInjector吗？

**Comment by gujiangjiang** [comment]
@scottsanett 有的啊。。。亮度调节，PNLF这些都是正常，10.11，10.12都是正常的，就装完10.13不行了。

**Comment by gujiangjiang** [comment]
@scottsanett 我想了一下，你是什么BIOS？？我昨天升级过BIOS，1.4.0了。。。

**Comment by gujiangjiang** [comment]
不可能貌似。。。新的DSDT没有修改DSDT部分的东西。。。等正式版出来再看。。。

**Comment by scottsanett** [comment]
@gujiangjiang 在1.3.0，1.4.0下载了点安装没反应遂放弃

**Comment by gujiangjiang** [comment]
可以看我的github，1.4.0的BIOS并没有对DSDT做修改，DSDT上次修改还是1.2.29，之后1.3.0和1.4.0都没有对DSDT进行修改，所以这个也不打可能

**Comment by darkhandz** [comment]
我还没升级BIOS，目前好像是1.2.29……10.13下还是正常的（VoodooPS2Controller）

@gujiangjiang  话说我的XG3没升级固件，终于Dirty Down导致掉盘了……默哀

**Comment by gujiangjiang** [comment]
@darkhandz 你不是用的Smart驱动？你用的Voodoo驱动？

XG3掉盘了？你是不是进入过ePSA故障诊断程序。。。XG3如果开启了4K扇区，就千万不能进入ePSA，进入就必掉盘。
掉盘后解决方法也有，但不是百试百灵，拆机，取下SSD，然后开机进入BIOS，然后找到硬盘设置，把M2选项去掉，然后运行一次ePSA，然后拆机把SSD插上去，开机会提示无固态，然后在进入BIOS，然后把M2选项勾上，迅速重启，不要关机，重启进入BIOS，如果看到首页M2里面有设备，说明回来了，如果还是没设备，那么继续重复上面的操作。

我提醒一下，尽量不要走售后，现在的售后不是XG4就是PM951，都是很垃圾很垃圾的盘，我之前为了更换固态想尽办法都不行，xg3还是不错的，能救回来就救回来，一旦换了就不可能再有的。

**Comment by gujiangjiang** [comment]
@darkhandz 
我测试了一下，用了你的SSDT-BRT6，用了你的VoodooPS2驱动，依旧不行啊。。。亮度快捷键还是不行，你现在是GM么？

**Comment by gujiangjiang** [comment]
@darkhandz 对了，有时间的话帮我看一下这个，这几个参数怎么一直注入不进去。。。IOREG里面看不到信息。。。

谢啦
[SSDT-SSD0.dsl.zip](https://github.com/darkhandz/XPS15-9550-High-Sierra/files/1309978/SSDT-SSD0.dsl.zip)

**Comment by darkhandz** [comment]
@gujiangjiang 我升级Beta8不小心异常重启了几次，玛德ePSA就自动起来了，按电源键都来不及，它就到了扫描SSD的步骤了！于是杯具发生…… 我还真准备报售后……等周六有空我按你方法试试先！

SSDT-BTR6.aml 还需要配合两个补丁使用，分别是图中的11、15，（11我估计你有了）：
![image](https://user-images.githubusercontent.com/2143333/30600697-c763600a-9d25-11e7-91a3-8bbd36e02a9c.png)

最后这个dsl还要看看才知道，我也不太熟DSDT，最近工作太忙了，建议优先请教syscl……（看他近期沉迷Clover无法自拔的样子）

**Comment by darkhandz** [comment]
@gujiangjiang 对了，有点特殊的就是，升级完系统的这次启动，或者刚安装完系统的这次启动，亮度调节是不生效的，第二次重启之后就生效了。

**Comment by gujiangjiang** [comment]
@darkhandz 你说的这几个Patch我都有，一个是BRT6重命名Patch，一个是OSSD，XOSI补丁我也有，10.11，10.12都是没问题的。。

你确定你是GM版本么。。。

**Comment by darkhandz** [comment]
![image](https://user-images.githubusercontent.com/2143333/30621608-b895046a-9d71-11e7-8dc8-a6a2d1a52fe5.png)

PNLF好像是按Rehabman教程和`AppleBacklightInjector.kext`一起生成的。


PS2K按键映射应该不影响，因为我FN+S和FN+B也是可以调节亮度的。
![image](https://user-images.githubusercontent.com/2143333/30621738-77dab126-9d72-11e7-88b3-d6655738469f.png)

**Comment by gujiangjiang** [comment]
太奇怪了，你这些我都跟你一样，但是我的F11，F12就是无效的。。。到底怎么回事愁死我了，排查了好久都没排出问题在哪里

**Comment by darkhandz** [comment]
@gujiangjiang 可以试试笨办法，用ACPIDebug.kext配合来看看DSDT方法执行到哪里：https://www.tonymacx86.com/threads/guide-using-clover-to-hotpatch-acpi.200137/page-3#post-1365198 这是我从前请教Rehabman的帖子，可以参考参考（那堆不讲语法拼凑的英文单词请自行忽略）

**Comment by gujiangjiang** [comment]
@darkhandz ACPIDebug我知道，但是需要修改DSDT。。。感觉好麻烦。。。有Hotpatch的办法配合ACPIDebug嘛

**Comment by gujiangjiang** [comment]
2017-09-20 11:46:07.821431+0800  localhost kernel[0]: (AppleACPIPlatform) <AppleACPIPlatform`AcpiOsVprintf> [\_SB.PCI0.LPCB.EC._Q66] (Node ffffff80477fb960)

2017-09-20 13:59:56.997191+0800  localhost kernel[0]: (kernel) ACPIDebug: "EC _Q66 enter"

**Comment by gujiangjiang** [comment]
Method (_Q66, 0, NotSerialized)  // _Qxx: EC Query
            {
                \RMDT.P1 ("EC _Q66 enter")
                If (LNotEqual (ECRD, One))
                {
                    Return (Zero)
                }

                NEVT ()
                Return (Zero)
                \RMDT.P1 ("EC _Q66 exit")
            }

**Comment by gujiangjiang** [comment]
Q66是如何Call SMEE的。。。我看了一下你发的那个帖子，没看懂上下文

**Comment by gujiangjiang** [comment]
解决了。。。

<img width="1160" alt="qq20170920-142905 2x" src="https://user-images.githubusercontent.com/13273955/30629732-1d304110-9da3-11e7-871d-75928593fc02.png">

OSSD补丁要早于XOSI补丁，不然就会出现亮度调节快捷键失效的问题。

把DSDT Patch的顺序调整一下，就OK了。

<img width="321" alt="a9b48148-5fb6-45b5-88a8-6e1a87c8fa90" src="https://user-images.githubusercontent.com/13273955/30629785-4bfa6a66-9da3-11e7-8169-e140b495d260.png">

谢谢啦。

**Comment by darkhandz** [comment]
@gujiangjiang 我config.plist图上是按顺序的，忘了跟你强调这个……哈哈，你搞定就好
